//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlykhachsandemo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class quanlykhachsanEntities2 : DbContext
    {
        public quanlykhachsanEntities2()
            : base("name=quanlykhachsanEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bangluong> bangluongs { get; set; }
        public virtual DbSet<bangthuephong> bangthuephongs { get; set; }
        public virtual DbSet<bophan> bophans { get; set; }
        public virtual DbSet<chucdanh> chucdanhs { get; set; }
        public virtual DbSet<cosovatchat> cosovatchats { get; set; }
        public virtual DbSet<dichvu> dichvus { get; set; }
        public virtual DbSet<hoadonchi> hoadonchis { get; set; }
        public virtual DbSet<hoadonthu> hoadonthus { get; set; }
        public virtual DbSet<hoivien> hoiviens { get; set; }
        public virtual DbSet<khachhang> khachhangs { get; set; }
        public virtual DbSet<loaidichvu> loaidichvus { get; set; }
        public virtual DbSet<loaiphong> loaiphongs { get; set; }
        public virtual DbSet<log> logs { get; set; }
        public virtual DbSet<nguoiocung> nguoiocungs { get; set; }
        public virtual DbSet<nhanvien> nhanviens { get; set; }
        public virtual DbSet<phanhoi> phanhois { get; set; }
        public virtual DbSet<phong> phongs { get; set; }
        public virtual DbSet<phongvattu> phongvattus { get; set; }
        public virtual DbSet<sudungdichvu> sudungdichvus { get; set; }
        public virtual DbSet<tinhtrang> tinhtrangs { get; set; }
        public virtual DbSet<trangthaithuephong> trangthaithuephongs { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
