//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlykhachsandemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoadonchi
    {
        public int id { get; set; }
        public string idnhanvien { get; set; }
        public string tennguoinhan { get; set; }
        public string lydo { get; set; }
        public Nullable<bool> chapnhan { get; set; }
        public Nullable<decimal> tongtien { get; set; }
    
        public virtual nhanvien nhanvien { get; set; }
    }
}
