//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlykhachsandemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class phongvattu
    {
        public int id { get; set; }
        public string idphong { get; set; }
        public string idcosovatchat { get; set; }
    
        public virtual cosovatchat cosovatchat { get; set; }
        public virtual phong phong { get; set; }
    }
}
