//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlykhachsandemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public string id { get; set; }
        public string pass { get; set; }
        public string idnhanvien { get; set; }
    
        public virtual nhanvien nhanvien { get; set; }
    }
}
